#!/usr/bin/php

<?php
error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Zilore\Commands\Ensure;

$app = new Application();
$app->add(new Ensure());
$app->run();

